export const movies = [
    {
        title: "Super 30",
        plot: "He thinks that these poor kids also have a right to study. Hence, he leaves Excellence and starts a separate tuition for poor kids, in which he enrolls 30 kids at a time. He teaches them to learn everything practically and have the concepts clear in an easy and fun way.",
        poster:"https://pix1.wapkizfile.info/download/86e8f47dc62e14cc1af152e3cd9bdb4d/filmy4wap+wapkiz+com/Super-30-2018-Bollywood-Hindi-Full-Movie-HD-ESub-(filmyfly.ink).jpg",
        rating: '9.1',
        price: 399,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "12th Fail",
        plot: "Born in the dacoit-infested Chambal, Manoj Kumar Sharma is the son of a clerk. His father, an honest man, is suspended for hitting a corrupt officer. Manoj prepares cheat slips for his Class 12 exams, as do all his batchmates.",
        poster:"https://pix1.wapkizfile.info/download/2784303c0922f8ac398f3b9c340d66b6/filmy4wap+wapkiz+com/12th-Fail-2023-Bollywood-Hindi-Full-Movie-HD-ESub-(filmyfly.ink).jpg",
        rating: '8.9',
        price: 199,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Sam Bahadur",
        plot: "In 1947, amidst the partition of the British Indian Army, Major Manekshaw is approached to join the Pakistan Army by his colleague, Yahya Khan; he chooses the Indian Army instead. Upon independence, discord emanates between the two countries over the sovereignty of Kashmir.",
        poster:"https://image.linkmake.in/images/files/1fb1a82714caeef46df763faa4019ae229437.png",
        rating: '7.6',
        price: 150,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "The Avengers",
        plot: "Earth's mightiest heroes must come together and learn to fight as a team if they ate going to stop the mischievous Loki and his alien army fromenslaving humanity.",
        poster:"https://www.movieposters.com/cdn/shop/products/108b520c55e3c9760f77a06110d6a73b_480x.progressive.jpg?v=1573652543",
        rating: '7.7',
        price: 199,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Mission Raniganj",
        plot: "the film follows the incredible journey of Jaswant Singh Gill, a dedicated mining engineer whose unwavering determination leads to the daring rescue of trapped miners in a flooded coal mine.",
        poster:"https://pix1.wapkizfile.info/download/ebaee144c2a8c23e819d0f1b56da4e9b/filmy4wap+wapkiz+com/Mission-Raniganj-2023-Bollywood-Hindi-Full-Movie-HD-ESub-(filmyfly.ink).jpg",
        rating: '8.1',
        price: 160,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Mission Mangal",
        plot: "Synopsis. After the failed launch of GSLV-F06 on 25 December 2010, due to a small mistake by Project Director Tara Shinde (Vidya Balan), Rakesh Dhawan (Akshay Kumar), a fellow scientist working with her, takes the blame for her. As a result, he is relocated to work on Mangalyaan as punishment.        ",
        poster:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIoZ6fzAfcXeALyOTz5jaxQBCkjOqBFtieO8FYJP7HbGzNSanCmbuaQ6oy3eW3r944MOs&usqp=CAU",
        rating: '7.4',
        price: 120,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Dashing CM Bharat",
        plot: "Bharat, an upright young man, is entrusted the chief ministerial position after the unexpected death of his father who was occupying that position. ",
        poster:"https://i1.iwebp.xyz/webp/120:130/100/CJEW4LsOK5M6HL9PrIokXnSk9LXFKi1itoX_p_lNgJuVaB9ZUaWUVUdrn0dPCKiZ4hfhTtsKjGn_p_uS_p_N5f2o_s_tvzuAD1iMLx3vkM_p_CeUA_p_JeSJZhCQZh_s_MGuPQ42ceZ3VNmCHo_s_FLnbgImWkBsQhYf5API0lotEcy87M0AC5x9_s_y0hKlkbM6AIIW1y0mrfSkr5BMceEjvVGco8fLUtg_s_ZNH8ZPWhnhAG_p_359x4tTZgAZtD9_p_ENI9fl5aqd15YFkEtRNw.webp",
        rating: '8.2',
        price: 170,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Darbar",
        plot: "Mumbai Police Commissioner Aditya Arunachalam is seen killing numerous gangsters across Mumbai in police encounters. His reckless behaviour has become the subject of widespread condemnation, which prompts the National Human Rights Commission of India to act against him.",
        poster:"https://i1.iwebp.xyz/webp/120:130/100/CJEW4LsOK5M6HL9PrIokXnSk9LXFKi1itoX_p_lNgJuVaB9ZUaWUUDJ7z1daGMiJ4sLke7t6zGmOmW_p_9xY193tvzqCXVuPLB3vkM_p_CeUA_p_JeSJZhCQZh_s_MGuPQ42cYbmZdmCfojwywc2EQW0A1blok5QTC3Fo6PYyX6IE2H4k84Fxldh08d5sCCzVSmkvFW1axbfo7U1PHGcx4O_s_4RgdhBDYd7GwbmDmvRyYFa.webp",
        rating: '8.3',
        price: 155,
        stars: 0,
        fav: false,
        isInCart: false,
    },
    {
        title: "Bheeshma",
        plot: "Bheeshma is the CEO of Bheeshma Organics who wants farmers to shift from using chemicals in farming to organic practices. Bheeshma gets them to shift in organic farming and announces to the media that he will announce the next CEO on the company's 50th anniversary.",
        poster:"https://i1.iwebp.xyz/webp/120:130/100/CJEW4LsOK5M6HL9PrIokXnSk9LXFKi1itoX_p_lNgJuVaB9ZUaWUVVd_p_infvXb2M1wfhrqt_s_iaze7CqohZ343ru2yEXlfcLR3vkM_p_CeUA_p_JeSJZhCQZh_s_MGuPQ42ceZ3Faij2o3BGwc35zGX0oaBMFoT7D2QIJKcy68c0eR6klqXR_s_PyE9GbsYZQZT22qHYFCiKddSNlK5Kf0gcbVQi9xUBpJkWRamDCyUit9XliQ.webp",
        rating: '7.2',
        price: 169,
        stars: 0,
        fav: false,
        isInCart: false,
    }
]